In [1]:
import pandas as pd
import seaborn as sb
import numpy as np
import matplotlib.pyplot as plt
sb.set()

In [4]:
filename_train_data = "Richters_Predictor_Modeling_Earthquake_Damage_-_Train_Values.csv"
filename_train_label = "Richters_Predictor_Modeling_Earthquake_Damage_-_Train_Labels.csv"
filename_test_data = "Richters_Predictor_Modeling_Earthquake_Damage_-_Test_Values.csv"

In [28]:
trainData = pd.read_csv(filename_train_data, 
                        dtype={
                            'land_surface_condition': 'category',
                            'foundation_type': 'category',
                            'roof_type': 'category',
                            'ground_floor_type': 'category',
                            'other_floor_type': 'category',
                            'position': 'category',
                            'plan_configuration': 'category',
                            'has_superstructure_adobe_mud': 'bool',
                            'has_superstructure_mud_mortar_stone': 'bool',
                            'has_superstructure_stone_flag': 'bool',
                            'has_superstructure_cement_mortar_stone': 'bool',
                            'has_superstructure_mud_mortar_brick': 'bool',
                            'has_superstructure_cement_mortar_brick': 'bool',
                            'has_superstructure_timber': 'bool',
                            'has_superstructure_bamboo': 'bool',
                            'has_superstructure_rc_non_engineered': 'bool',
                            'has_superstructure_rc_engineered': 'bool',
                            'has_superstructure_other': 'bool',
                            'legal_ownership_status': 'category',
                            'has_secondary_use': 'bool',
                            'has_secondary_use_agriculture': 'bool',
                            'has_secondary_use_hotel': 'bool',
                            'has_secondary_use_rental': 'bool',
                            'has_secondary_use_institution': 'bool',
                            'has_secondary_use_school': 'bool',
                            'has_secondary_use_industry': 'bool',
                            'has_secondary_use_health_post': 'bool',
                            'has_secondary_use_gov_office': 'bool',
                            'has_secondary_use_use_police': 'bool',
                            'has_secondary_use_other': 'bool'
                        })
trainLabel = pd.read_csv(filename_train_label,
                        dtype={
                            'damage_grade': 'category'
                        })

In [29]:
trainData.head()

,building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,...,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,802906,6,487,12198,2,30,6,5,t,r,...,False,False,False,False,False,False,False,False,False,False
1,28830,8,900,2812,2,10,8,7,o,r,...,False,False,False,False,False,False,False,False,False,False
2,94947,21,363,8973,2,10,5,5,t,r,...,False,False,False,False,False,False,False,False,False,False
3,590882,22,418,10694,2,10,6,5,t,r,...,False,False,False,False,False,False,False,False,False,False
4,201944,11,131,1488,3,30,8,9,t,r,...,False,False,False,False,False,False,False,False,False,False

In [30]:
trainLabel.head()

   building_id damage_grade
0       802906            3
1        28830            2
2        94947            3
3       590882            2
4       201944            3

In [31]:
trainData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260601 entries, 0 to 260600
Data columns (total 39 columns):
building_id                               260601 non-null int64
geo_level_1_id                            260601 non-null int64
geo_level_2_id                            260601 non-null int64
geo_level_3_id                            260601 non-null int64
count_floors_pre_eq                       260601 non-null int64
age                                       260601 non-null int64
area_percentage                           260601 non-null int64
height_percentage                         260601 non-null int64
land_surface_condition                    260601 non-null category
foundation_type                           260601 non-null category
roof_type                                 260601 non-null category
ground_floor_type                         260601 non-null category
other_floor_type                          260601 non-null category
position                                  260601 non-null category
plan_configuration                        260601 non-null category
has_superstructure_adobe_mud              260601 non-null bool
has_superstructure_mud_mortar_stone       260601 non-null bool
has_superstructure_stone_flag             260601 non-null bool
has_superstructure_cement_mortar_stone    260601 non-null bool
has_superstructure_mud_mortar_brick       260601 non-null bool
has_superstructure_cement_mortar_brick    260601 non-null bool
has_superstructure_timber                 260601 non-null bool
has_superstructure_bamboo                 260601 non-null bool
has_superstructure_rc_non_engineered      260601 non-null bool
has_superstructure_rc_engineered          260601 non-null bool
has_superstructure_other                  260601 non-null bool
legal_ownership_status                    260601 non-null category
count_families                            260601 non-null int64
has_secondary_use                         260601 non-null bool
has_secondary_use_agriculture             260601 non-null bool
has_secondary_use_hotel                   260601 non-null bool
has_secondary_use_rental                  260601 non-null bool
has_secondary_use_institution             260601 non-null bool
has_secondary_use_school                  260601 non-null bool
has_secondary_use_industry                260601 non-null bool
has_secondary_use_health_post             260601 non-null bool
has_secondary_use_gov_office              260601 non-null bool
has_secondary_use_use_police              260601 non-null bool
has_secondary_use_other                   260601 non-null bool
dtypes: bool(22), category(8), int64(9)
memory usage: 25.4 MB

In [32]:
trainLabel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260601 entries, 0 to 260600
Data columns (total 2 columns):
building_id     260601 non-null int64
damage_grade    260601 non-null category
dtypes: category(1), int64(1)
memory usage: 2.2 MB